# src/main/resources/application-dev.yml
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    cz.stavbau: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

meteostat:
  enabled: false