spring:
  application:
    name: stavbau-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/stavbau
    username: stavbau
    password: stavbau
    hikari:
      connectionInitSql: "SET search_path TO public"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: public
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    clean-disabled: true  # jen dočasně na reset
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

app:
  security:
    cookies:
      secure: false
    bcrypt-cost: 12
    jwt:
      issuer: "stavbau"
      accessTokenTtlMinutes: 30
      refreshTokenTtlDays: 14
      secret: "hkCeFiMnK/WnZlQn9JvxguLMB7LEBXxM05E86Gg2Eirg0CWmrKvH1dG0lfcTBwwECiIyw1/Cc4Mgk0qLA6rlpg=="
      rbacClaimsEnabled: true
    rbac:
      claims:
        enabled: false  # default = stabilní login bez RBAC claimů

# <<< PŘESUNUTO DO DEFAULTU
mapycz:
  base-url: "https://api.mapy.com"
  api-key: "ZD4dB8zouM7Zn727KU6u_iTM2pOk31djjAnlqsq3jiQ"  # "${MAPYCZ_API_KEY}"  klíč držíme v ENV / CI secrets
  timeout-ms: 2500

meteostat:
  enabled: true
  base-url: "https://meteostat.p.rapidapi.com"
  sessions-url: "${meteostat.base-url}"   # ← tohle vyžaduje @Value v configu
  rapidapi:
    host: "meteostat.p.rapidapi.com"
    key:  "440c5b540cmsh1379b04a05dc3eap1fde53jsn01f3e9c63e1e"   # nastav v ENV / docker secrets, NEcommitovat!
  timeout-ms: 5000

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    cz.stavbau: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

files:
  storage:
    type: local
    local:
      base-path: /mnt/data/stavbau-data/files
  upload:
    max-size-mb: 25
    allowed-mime:
      - application/pdf
      - image/png
      - image/jpeg
      - text/plain
