name: CI - Backend (Spring Boot)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Run tests
        run: mvn -B test

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: |
            **/target/*.jar
